name: Monitor Criterion 24h

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando os arquivos
        uses: actions/checkout@v4 # Atualizado para v4

      - name: Preparando o Node.js
        uses: actions/setup-node@v4 # Atualizado para v4
        with:
          node-version: '24' # Versão mais atual recomendada

      - name: Instalando dependências
        run: npm install puppeteer

      - name: Executando a captura
        run: node scraper.js

      - name: Salvando os dados
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git add programacao.csv
          git commit -m "Captura automatica: $(date)" || echo "Sem mudanças para salvar"
          git push
