name: Monitor Criterion 24h

on:
  schedule:
    - cron: '0,15,30,45 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install puppeteer

      - name: Execute Scraper
        run: node scraper.js

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add programacao.csv
          git commit -m "Registro automático: $(date +'%d/%m %H:%M')" || exit 0
          git push
